services:
  clientes:
    build:
      context: .
      dockerfile: ./ClienteService/Dockerfile
    container_name: clientes_api
    ports:
      - "8001:80"
    volumes:
      - ./ClienteService/app:/code/app
      - ./conexao:/code/conexao

  gerenciarbens:
    build:
      context: .
      dockerfile: ./GerenciarBensService/Dockerfile
    container_name: gerenciarbens_api
    ports:
      - "8002:80"
    volumes:
      - ./GerenciarBensService/app:/code/app
      - ./conexao:/code/conexao